apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- virtual-service.yaml

vars:
- fieldref:
    fieldPath: metadata.namespace
  name: namespace
  objref:
    apiVersion: v1
    kind: VirtualService
    name: kfam

configurations:
- params.yaml
