apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: $(acmeEmail)
    privateKeySecretRef:
      name: letsencrypt-prod-secret
    server: $(acmeUrl)
    solvers:
    - http01:
        ingress:
          class: nginx
